apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql_secret.name }}
  labels:
    app: {{ .Values.mysql_secret.labels.app }}
type: {{ .Values.mysql_secret.type }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql_secret.data.root_password }}
  MYSQL_DATABASE: {{ .Values.mysql_secret.data.database }}
  MYSQL_USER: {{ .Values.mysql_secret.data.user }}
  MYSQL_PASSWORD: {{ .Values.mysql_secret.data.mysql_password }}
