apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql_service.name }}
  labels:
    app: {{ .Values.mysql_service.name }}
spec:
  type: {{ .Values.mysql_service.type }}
  ports:
  - port: {{ .Values.mysql_service.port }}
    targetPort: {{ .Values.mysql_service.targetport }}
    protocol: {{ .Values.mysql_service.protocol }}
  selector:
    app: {{ .Values.mysql_service.name }}
