apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.python_secret.name }}
  labels:
    app: {{ .Values.python_secret.labels }}
type: {{ .Values.python_secret.type }}
data:
  DB_USER: "{{ .Values.python_secret.db_user }}"  # Base64 encoded value for "aaqib"
  DB_PASS: "{{ .Values.python_secret.db_password }}"  # Base64 encoded value for "admin"
