apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment.name }}
  labels:
    app: {{ .Values.environment.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.environment.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 # Optional, Kubernetes will auto-assign if not specified
